name: docker-build-push
on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and publish
        run: |
          TAG=$(echo $GITHUB_REF | grep -o "[0-9][\.].*")
          echo Imag teg is: $TAG
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker build --build-arg BUILD_VERSION=$TAG -t gkarthics/vault-balancer:$TAG .
          docker push gkarthics/vault-balancer
